// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: developer.proto

package task.prot;

public final class DeveloperProto {
  private DeveloperProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code prot.ProgrammingLanguage}
   */
  public enum ProgrammingLanguage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JAVA = 1;</code>
     */
    JAVA(0, 1),
    /**
     * <code>PYTHON = 2;</code>
     */
    PYTHON(1, 2),
    /**
     * <code>SCALA = 3;</code>
     */
    SCALA(2, 3),
    /**
     * <code>JAVA_SCRIPT = 4;</code>
     */
    JAVA_SCRIPT(3, 4),
    ;

    /**
     * <code>JAVA = 1;</code>
     */
    public static final int JAVA_VALUE = 1;
    /**
     * <code>PYTHON = 2;</code>
     */
    public static final int PYTHON_VALUE = 2;
    /**
     * <code>SCALA = 3;</code>
     */
    public static final int SCALA_VALUE = 3;
    /**
     * <code>JAVA_SCRIPT = 4;</code>
     */
    public static final int JAVA_SCRIPT_VALUE = 4;


    public final int getNumber() { return value; }

    public static ProgrammingLanguage valueOf(int value) {
      switch (value) {
        case 1: return JAVA;
        case 2: return PYTHON;
        case 3: return SCALA;
        case 4: return JAVA_SCRIPT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProgrammingLanguage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProgrammingLanguage>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProgrammingLanguage>() {
            public ProgrammingLanguage findValueByNumber(int number) {
              return ProgrammingLanguage.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return task.prot.DeveloperProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProgrammingLanguage[] VALUES = values();

    public static ProgrammingLanguage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProgrammingLanguage(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:prot.ProgrammingLanguage)
  }

  public interface DeveloperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prot.Developer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string phone = 3;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional string phone = 3;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    java.util.List<task.prot.DeveloperProto.ProgrammingLanguage> getKnownLanguagesList();
    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    int getKnownLanguagesCount();
    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    task.prot.DeveloperProto.ProgrammingLanguage getKnownLanguages(int index);
  }
  /**
   * Protobuf type {@code prot.Developer}
   */
  public static final class Developer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:prot.Developer)
      DeveloperOrBuilder {
    // Use Developer.newBuilder() to construct.
    private Developer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Developer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Developer defaultInstance;
    public static Developer getDefaultInstance() {
      return defaultInstance;
    }

    public Developer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Developer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              phone_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              task.prot.DeveloperProto.ProgrammingLanguage value = task.prot.DeveloperProto.ProgrammingLanguage.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  knownLanguages_ = new java.util.ArrayList<task.prot.DeveloperProto.ProgrammingLanguage>();
                  mutable_bitField0_ |= 0x00000008;
                }
                knownLanguages_.add(value);
              }
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                task.prot.DeveloperProto.ProgrammingLanguage value = task.prot.DeveloperProto.ProgrammingLanguage.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    knownLanguages_ = new java.util.ArrayList<task.prot.DeveloperProto.ProgrammingLanguage>();
                    mutable_bitField0_ |= 0x00000008;
                  }
                  knownLanguages_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          knownLanguages_ = java.util.Collections.unmodifiableList(knownLanguages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return task.prot.DeveloperProto.internal_static_prot_Developer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return task.prot.DeveloperProto.internal_static_prot_Developer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              task.prot.DeveloperProto.Developer.class, task.prot.DeveloperProto.Developer.Builder.class);
    }

    public static com.google.protobuf.Parser<Developer> PARSER =
        new com.google.protobuf.AbstractParser<Developer>() {
      public Developer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Developer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Developer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    private java.lang.Object phone_;
    /**
     * <code>optional string phone = 3;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KNOWNLANGUAGES_FIELD_NUMBER = 4;
    private java.util.List<task.prot.DeveloperProto.ProgrammingLanguage> knownLanguages_;
    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    public java.util.List<task.prot.DeveloperProto.ProgrammingLanguage> getKnownLanguagesList() {
      return knownLanguages_;
    }
    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    public int getKnownLanguagesCount() {
      return knownLanguages_.size();
    }
    /**
     * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
     */
    public task.prot.DeveloperProto.ProgrammingLanguage getKnownLanguages(int index) {
      return knownLanguages_.get(index);
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      phone_ = "";
      knownLanguages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPhoneBytes());
      }
      for (int i = 0; i < knownLanguages_.size(); i++) {
        output.writeEnum(4, knownLanguages_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPhoneBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < knownLanguages_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(knownLanguages_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * knownLanguages_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static task.prot.DeveloperProto.Developer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static task.prot.DeveloperProto.Developer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static task.prot.DeveloperProto.Developer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static task.prot.DeveloperProto.Developer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(task.prot.DeveloperProto.Developer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prot.Developer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prot.Developer)
        task.prot.DeveloperProto.DeveloperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return task.prot.DeveloperProto.internal_static_prot_Developer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return task.prot.DeveloperProto.internal_static_prot_Developer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                task.prot.DeveloperProto.Developer.class, task.prot.DeveloperProto.Developer.Builder.class);
      }

      // Construct using task.prot.DeveloperProto.Developer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        knownLanguages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return task.prot.DeveloperProto.internal_static_prot_Developer_descriptor;
      }

      public task.prot.DeveloperProto.Developer getDefaultInstanceForType() {
        return task.prot.DeveloperProto.Developer.getDefaultInstance();
      }

      public task.prot.DeveloperProto.Developer build() {
        task.prot.DeveloperProto.Developer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public task.prot.DeveloperProto.Developer buildPartial() {
        task.prot.DeveloperProto.Developer result = new task.prot.DeveloperProto.Developer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phone_ = phone_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          knownLanguages_ = java.util.Collections.unmodifiableList(knownLanguages_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.knownLanguages_ = knownLanguages_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof task.prot.DeveloperProto.Developer) {
          return mergeFrom((task.prot.DeveloperProto.Developer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(task.prot.DeveloperProto.Developer other) {
        if (other == task.prot.DeveloperProto.Developer.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPhone()) {
          bitField0_ |= 0x00000004;
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.knownLanguages_.isEmpty()) {
          if (knownLanguages_.isEmpty()) {
            knownLanguages_ = other.knownLanguages_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureKnownLanguagesIsMutable();
            knownLanguages_.addAll(other.knownLanguages_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        task.prot.DeveloperProto.Developer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (task.prot.DeveloperProto.Developer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 3;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            phone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 3;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        phone_ = value;
        onChanged();
        return this;
      }

      private java.util.List<task.prot.DeveloperProto.ProgrammingLanguage> knownLanguages_ =
        java.util.Collections.emptyList();
      private void ensureKnownLanguagesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          knownLanguages_ = new java.util.ArrayList<task.prot.DeveloperProto.ProgrammingLanguage>(knownLanguages_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public java.util.List<task.prot.DeveloperProto.ProgrammingLanguage> getKnownLanguagesList() {
        return java.util.Collections.unmodifiableList(knownLanguages_);
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public int getKnownLanguagesCount() {
        return knownLanguages_.size();
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public task.prot.DeveloperProto.ProgrammingLanguage getKnownLanguages(int index) {
        return knownLanguages_.get(index);
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public Builder setKnownLanguages(
          int index, task.prot.DeveloperProto.ProgrammingLanguage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKnownLanguagesIsMutable();
        knownLanguages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public Builder addKnownLanguages(task.prot.DeveloperProto.ProgrammingLanguage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKnownLanguagesIsMutable();
        knownLanguages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public Builder addAllKnownLanguages(
          java.lang.Iterable<? extends task.prot.DeveloperProto.ProgrammingLanguage> values) {
        ensureKnownLanguagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, knownLanguages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .prot.ProgrammingLanguage knownLanguages = 4;</code>
       */
      public Builder clearKnownLanguages() {
        knownLanguages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:prot.Developer)
    }

    static {
      defaultInstance = new Developer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:prot.Developer)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prot_Developer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prot_Developer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017developer.proto\022\004prot\"g\n\tDeveloper\022\014\n\004" +
      "name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005phone\030\003 \001(\t\0221\n" +
      "\016knownLanguages\030\004 \003(\0162\031.prot.Programming" +
      "Language*G\n\023ProgrammingLanguage\022\010\n\004JAVA\020" +
      "\001\022\n\n\006PYTHON\020\002\022\t\n\005SCALA\020\003\022\017\n\013JAVA_SCRIPT\020" +
      "\004B\033\n\ttask.protB\016DeveloperProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_prot_Developer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prot_Developer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_prot_Developer_descriptor,
        new java.lang.String[] { "Name", "Id", "Phone", "KnownLanguages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
